#!/bin/sh
set -e
# copy file so volumn can share existint database;
#cp /data/.drupal.sqlite /data/.drupal.sqlite
mv /tmp/.drupal.sqlite /data/drupal.sqlite
sed -i "s#\/tmp\/\.drupal\.sqlite#\/data\/drupal\.sqlite#g" /opt/drupal/web/sites/default/settings.php
drush -r /opt/drupal/ cr
chmod -R 777 /data

if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

exec "$@"
