name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'Why??'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - drupal_version: 9
         - drupal_version: 10

    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        tags: zterry95/drupal-quick:${{ matrix.drupal_version }}
        build-args: DRUPAL_VERSION=${{ matrix.drupal_version }}
